version: '3'
services:
  wordpress:
    image: visiblevc/wordpress

    # required for mounting bindfs
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse

    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./app:/app
      - ./data:/data
      - ./theme-virgo-coop:/app/wp-content/themes/virgo-coop
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
        [wp-graphql]https://github.com/wp-graphql/wp-graphql/archive/v0.0.29.zip

  db:
    image: mariadb:10  # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 22222:80

volumes:
  data:
